#include "w1tn3ss.hpp"
#include <iostream>

// Build information - could be generated by CMake
#ifndef W1TN3SS_VERSION
#define W1TN3SS_VERSION "0.1.0-dev"
#endif

#ifndef W1TN3SS_BUILD_INFO
#define W1TN3SS_BUILD_INFO "development build"
#endif

namespace w1 {

const char* w1tn3ss::version() {
    return W1TN3SS_VERSION;
}

const char* w1tn3ss::build_info() {
    return W1TN3SS_BUILD_INFO;
}

void w1tn3ss::print_info() {
    std::cout << "w1tn3ss " << version() << std::endl;
    std::cout << "Build: " << build_info() << std::endl;
    std::cout << "Cross-platform dynamic binary analysis framework" << std::endl;
}

} // namespace w1